scenario: test1

run_settings:
  run_time: 2000
  warmup_time: 100
  num_replications: 5

paths:
  stop_logs: ./logs
  occ_logs: ./logs
  occ_stats: ./stats

global_vars:
  arrival_rate: 0.4
  mean_los_obs: 3.0
  num_erlang_stages_obs: 4
  mean_los_ldr: 12.0
  num_erlang_stages_ldr: 4
  mean_los_pp_c: 72.0
  mean_los_pp_noc: 48.0
  num_erlang_stages_pp: 4
  mean_los_csect: 1
  num_erlang_stages_csect: 4
  c_sect_prob: 0.15

random_number_streams:
  arrivals: 27
  los: 19

locations:
  0:
    id: 0
    name: ENTRY
    capacity: 1000
  1:
    id: 1
    name: OBS
    capacity: 10
  2:
    id: 2
    name: LDR
    capacity: 15
  3:
    id: 3
    name: CSECT
    capacity: 1000
  4:
    id: 4
    name: PP
    capacity: 35
  5:
    id: 5
    name: EXIT
    capacity: 1000

routes:
  1:
    id: 1
    edges:
      - id: 0
        from: 0
        to: 1
      - id: 1
        from: 1
        to: 2
      - id: 2
        from: 2
        to: 4
      - id: 3
        from: 4
        to: 5
  2:
    id: 2
    edges:
      - id: 0
        from: 0
        to: 1
      - id: 1
        from: 1
        to: 2
      - id: 2
        from: 2
        to: 3
      - id: 3
        from: 3
        to: 4
      - id: 4
        from: 4
        to: 5