run_settings:
  run_time: 60000
  warmup_time: 0
  num_replications: 5

paths:
  stop_logs: ./logs
  occ_logs: ./logs
  occ_stats: ./stats
  output: ./output

random_number_streams:
  arrivals: 27
  los: 19

locations:
  0:
    id: 0
    name: ENTRY
    capacity: 1000
  1:
    id: 1
    name: OBS
    capacity: 4
  2:
    id: 2
    name: LDR
    capacity: 2
  3:
    id: 3
    name: CSECT
    capacity: 1000
  4:
    id: 4
    name: PP
    capacity: 9
  5:
    id: 5
    name: EXIT
    capacity: 1000

routes:
  1:
    id: 1
    edges:
      - id: 0
        from: 0
        to: 1
      - id: 1
        from: 1
        to: 2
      - id: 2
        from: 2
        to: 4
      - id: 3
        from: 4
        to: 5
  2:
    id: 2
    edges:
      - id: 0
        from: 0
        to: 1
      - id: 1
        from: 1
        to: 2
      - id: 2
        from: 2
        to: 3
      - id: 3
        from: 3
        to: 4
      - id: 4
        from: 4
        to: 5